### ISSUE TITLE
Erreur sur des agences

### ISSUE THREAD

**Issue by Jean-BaptisteC** [cartesapp/serveur#32]
J'ai des erreurs sur certains liens d'agence sur la page `transport-en-commun` sur la Bretagne
- [x] https://cartes.app/?transports=oui&agence=RIV
- [x] https://cartes.app/?transports=oui&agence=SNCF (ça sent le doublon)
- [x] https://cartes.app/?transports=oui&agence=LINEOTIML30

Réseau européen Eurostar
- [ ] https://cartes.app/?transports=oui&agence=EUROSTAR
- [ ] https://cartes.app/?transports=oui&agence=X327

Réseau européen Thalys
- [ ] https://cartes.app/?transports=oui&agence=TH

Auvergne-Rhône-Alpes
- [ ] https://cartes.app/?transports=oui&agence=PRIVAS:Operator:T-CAP

Normandie
- [ ] https://cartes.app/?transports=oui&agence=ATOUMOD103:Network:103:LOC (Navette du Mont-Saint Michel)

**Comment by laem** [comment]
Ça semble être un pb de génération des "agencyAreas" côté serveur. À investiguer.

**Comment by Jean-BaptisteC** [comment]
Avec l'ajout du préfixe, tous les agences ont changés de nom, est ce qu'on pourrait pas avoir une log des agences en erreur, même si je pense que la plupart sont corrigés 😉

**Comment by laem** [comment]
Il faut que je me replonge dans le sujet, mais justement c'est pas simple, car il faut caractériser ce qu'est une erreur.

**Comment by Jean-BaptisteC** [comment]
Ok, je vais essayer de te trouver de nouveaux exemples

**Comment by Jean-BaptisteC** [comment]
Toutes les agences ont été testés, je ferme le ticket
